apiVersion: graybox.anthosapis.com/v1alpha1
kind: InstanceSet
metadata:
  name: system-generated-ignore
spec:
  appProperties:
    envs:
    - name: prod
      # includeInReleasePipeline: true
      # releasePipelinePreviousEnvironmentDelay: 168h

